% Creating a Manual Fitness Function
%
% ATheNA requires a manual fitness function in order to work. This function
% is written by the user to calculate a manual fitness value in the range
% [-1, 1], where -1 is most desirable and 1 is least desirable. The
% function definition must be the following, where 'myFitnessFunction' can
% be replaced with any name.
%
% Usage:
%
% fitness = myFitnessFunction(t,u,y)
%
% DESCRIPTION :
%
%   The manual fitness function is defined by the user with whatever metric
%   the user desires to indicate a better outcome for falsification. This
%   allows ATheNA to combine automatically calculated fitness with a user's
%   domain knowledge to better guide the search for falsification.
% 
%   The structure of the function MUST follow the usage pattern, with the
%   exception that the name of the function can be any legal function name.
%   It uses the timestamps of the simulation (t), the input (u), which can
%   be either the interpolated signals or only the control points values,
%   and the output (y) at each timestamp for each output port.
% 
%   Global variables can also be invoked inside of the function to
%   calculate the fitness function, but there must be only 3 inputs to the
%   fitness function.
%
%   The function must be provided to the athena_options.fitnessFcn
%   property. If the function is a main function, then the name must be
%   provided as a string or character vector. If it is stored as a local or
%   nested function, then provide the function handle instead. Ensure that
%   the file in which the function is located exists on the MATLAB path.
%   See documentation: <a href="matlab: doc
%   athena_options.fitnessFcn">athena_options.fitnessFcn</a>
%
% INPUTS :
%
%   - t : column vector of timestamps spanning the simulation time.
%
%   - u : simulation model inputs. Can be of type:
%     * column vector : 
%
%       All the control points generated by staliro for the current
%       iteration. This is only given if athena_options.useInterpInput is
%       set to false. 
%       See documentation: <a href="matlab: doc athena_options.useInterpInput">athena_options.useInterpInput</a>
%
%     * matrix :
%       The interpolated signals for each input, where the ith column is
%       the signal for the ith input port. The rows correspond with the
%       timestamps in t. This is given if athena_options.useInterpInput is
%       set to true.
%       See documentation: <a href="matlab: doc athena_options.useInterpInput">athena_options.useInterpInput</a>
%
%   - y : matrix with the output signals of the model, where the ith column
%     is the output for the ith port. The rows correspond to the
%     timestamps in t.
%
% OUTPUTS :
%
%   - fitness : the calculated manual fitness of the current test, which is
%       scaled if needed to a number in the range [-1, 1], where -1 is most
%       desirable, and 1 is least desirable.
%
% See also: athena_options, athena_options.fitnessFcn,
% athena_options.coeffRob
function fitness = createManualFitness(t,u,y)
fitness = 1;
end

