function GenerateOutputWindow(athena_opt, cp_array, preds, run_num)
% GENERATEOUTPUTWINDOW Creates the relevant window for ATheNA output if
% Nfig is >= 0.
%   Creates a progress bar window if Nfig is 0, otherwise creates 2 figures
%   with the first figure numbered Nfig if Nfig is greater than 0, and
%   Nfig+1 for the second window. The first window shows the input for the
%   model, and the second window shows the output generated by the model.
%   If label names are provided for the y-labels, they are used, otherwise
%   the y-labels are numbered by their index.
if athena_opt.Nfig == 0
    W = waitbar(0,'Running ATheNA-S.');
elseif athena_opt.Nfig > 0
    % Check and create the necessary y-labels
    if isempty(athena_opt.InputLabels)
        athena_opt.InputLabels = cell(length(cp_array));
        for ii = 1:length(cp_array)
            if strcmp(athena_opt.LabelInterpreter, 'latex')
                athena_opt.InputLabels{ii} = sprintf('$Input~%i',ii);
            else
                athena_opt.InputLabels{ii} = sprintf('Input %i',ii);
            end
        end
    end
    if isempty(athena_opt.OutputLabels)
        athena_opt.OutputLabels = cell(length(preds(1).A));
        for ii = 1:length(preds(1).A)
            if strcmp(athena_opt.LabelInterpreter, 'latex')
                athena_opt.OutputLabels{ii} = sprintf('$Output~%i',ii);
            else
                athena_opt.OutputLabels{ii} = sprintf('Output %i', ii);
            end
        end
    end
end

% Initialize window
if athena_opt.Nfig == 0
    % Update waitbar
    WaitStr = sprintf('Current run: %i/%i',run_num,athena_opt.athena_runs);
    waitbar(run_num/athena_opt.athena_runs,W,WaitStr)
elseif athena_opt.Nfig > 0
    % Input plot
    figure(athena_opt.Nfig)
    clf
    for jj = 1:length(cp_array)
        subplot(length(cp_array),1,jj)
        if strcmp(athena_opt.LabelInterpreter, 'latex')
            xlabel('$Time~[s]$','Interpreter','latex','FontSize',14)
        else
            xlabel('Time [s]','Interpreter',athena_opt.LabelInterpreter,'FontSize',14)
        end
        ylabel(athena_opt.InputLabels{jj},'Interpreter',athena_opt.LabelInterpreter,'FontSize',14)
    end
    TitleStr = sprintf('Input - Run %i/%i',run_num,athena_opt.athena_runs);
    if strcmp(athena_opt.LabelInterpreter,'latex')
        TitleStr = sprintf('$Input~-~Run~%i/%i$',run_num,athena_opt.athena_runs);
    end
    sgtitle(TitleStr,'Interpreter',athena_opt.LabelInterpreter,'FontSize',20)

    % Output plot
    figure(athena_opt.Nfig+1)
    clf
    for jj = 1:length(preds(1).A)
        subplot(length(preds(1).A),1,jj)
        if strcmp(athena_opt.LabelInterpreter, 'latex')
            xlabel('$Time~[s]$','Interpreter','latex','FontSize',14)
        else
            xlabel('Time [s]','Interpreter',athena_opt.LabelInterpreter,'FontSize',14)
        end
        ylabel(athena_opt.OutputLabels{jj},'Interpreter',athena_opt.LabelInterpreter,'FontSize',14)
    end
    TitleStr = sprintf('Output - Run %i/%i',run_num,athena_opt.athena_runs);
    if strcmp(athena_opt.LabelInterpreter,'latex')
        TitleStr = sprintf('$Output~-~Run~%i/%i$',run_num,athena_opt.athena_runs);
    end
    sgtitle(TitleStr,'Interpreter',athena_opt.LabelInterpreter,'FontSize',20)
end
end

